version: 1
commands:
  package:
    - rm -f dist/*.lua
    - mercury luabundle
    - mercury luabundle server
    - cp -f dist/mimic_server.lua package/lua-sapp
    - cp -f dist/mimic.lua package/balltze-plugins/mimic.lua
    - mercury pack package/ dist/
    - rm -f package/balltze-plugins/mimic.lua
    - rm -f package/lua-sapp/mimic_server.lua
  symlinks:
    - ln -f -s "$PWD/dist/mimic_server.lua" "$HALO_CE_DATA_PATH/sapp/lua/mimic_server.lua"
  release:
    - mercury build package